"use strict";
exports.__esModule = true;
var LinkList_1 = require("./LinkList");
var linkedList = new LinkList_1.LinkedList();
linkedList.insertFirstNode(1);
linkedList.insertFirstNode(2);
linkedList.insertFirstNode(3);
linkedList.insertFirstNode(10);
linkedList.insertLastNode(40);
console.log(linkedList.getSize());
console.log(linkedList.readList());
